### ISSUE TITLE
Typo in variable name "slo_forwad_on_logout"

### ISSUE THREAD

**Issue by protag** [bluedatainc/jupyterhub-samlauthenticator#40]
In the README.md, it says:

> The SAMLAuthenticator usually attempts to forward users to the SLO URI set in the SAML Metadata. If this is not the desired behavior for whatever reason, set slo_forward_on_logout to False. This will change the page the user is forwarded to on logout from the page specified in the xml metadata to the standard jupyterhub logout page.

However, the example config in the README and the code itself uses the variable name "slo_forwad_on_logout".

**Comment by distortedsignal** [comment]
Wow, can't believe that I screwed that up.

**Comment by distortedsignal** [comment]
I think I would prefer that this be taken on in a non-breaking way - no reason to cause current configs to become invalid - but to prefer the proper spelling.
