### ISSUE TITLE
c.Authenticator.whitelist not supported?

### ISSUE THREAD

**Issue by jeffmaley** [bluedatainc/jupyterhub-samlauthenticator#57]
From testing, it doesn't look like c.Authenticator.whitelist is supported by this authenticator. Is that expected and, if so, is it planned for a future release?

**Comment by distortedsignal** [comment]
Hmmmm... it should be. Could you go into the behavior that you're seeing, the behavior that you expect to see, and any logs that might help shed light on the issue?

**Comment by jeffmaley** [comment]
Regardless of what names I configure in c.Authenticator.whitelist in jupyterhub_config.py, any user seems to be able to authenticate and get in. My goal is to allow only a specified user to login. I can see that's it's acknowledging the line exists because there's no log entry like:
_Not using whitelist. Any authenticated user will be allowed._

It looks like the jupyterhub made some changes (github.com/jupyterhub/jupyterhub/pull/3090), but it looks like they should still support the existing language.

**Comment by distortedsignal** [comment]
Good catch. Could you send me the relevant lines in your config file?

**Comment by jeffmaley** [comment]
Here's the config:
c.JupyterHub.authenticator_class = 'samlauthenticator.SAMLAuthenticator'
c.SAMLAuthenticator.metadata_filepath = <redacted>
c.SAMLAuthenticator.audience = 'http://localhost:8000/'
c.SAMLAuthenticator.recipient = 'http://localhost:8002/hub/login'
c.SAMLAuthenticator.acs_endpoint_url = 'http://localhost:8001:/hub/login'
c.SAMLAuthenticator.time_format_string = '%Y-%m-%dT%H:%M:%S.%fZ'
c.SAMLAuthenticator.create_system_users = True
c.SAMLAuthenticator.slo_forward_on_logout = True
c.Authenticator.whitelist = {'maleyjm'}

**Comment by distortedsignal** [comment]
Ah, I see the issue - I think that `c.Authenticator.whitelist` should probably be `c.SAMLAuthenticator.whitelist`.

**Comment by jeffmaley** [comment]
I gave that a whirl and jupyterhub logged that no whitelist was configured. I'm going to start with a fresh instance tomorrow, as I've done a number of things to this one and the behavior is completely different from the first instance I setup.

**Comment by jeffmaley** [comment]
I did a fresh setup and the whitelist works, so I'm assuming I screwed something up on the previous installs.

**Comment by distortedsignal** [comment]
It happens. I'm glad that the whitelist feature works now :)
